### ISSUE TITLE
[Feature] Ignore LF/CRLF differences

### ISSUE THREAD

**Issue by C0ZEN** [tj-actions/verify-changed-files#101]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I think that I have an issue because locally, I am pushing CLRF files and on my CI, I recreate them and perform the diff (on a folder).
This action is telling me that there is a difference and a warning about the EOL is visible (seems logical since the CI is using Linux).

### Describe the solution you'd like?

Add a new input to ignore the EOL (default is false to not create a breaking change).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by C0ZEN** [comment]
@jackton1 thank you for taking care of this.
I checked if something has changed with the latest version. 
However, I still have the same issue.

If you need more insights, here is the failing step https://github.com/Sonia-corporation/stale/runs/4130318260?check_suite_focus=true.

**Comment by jackton1** [comment]
@C0ZEN sorry for the mix up this was fixed in a different action, I’ll make the same change and deploy it later today

**Comment by jackton1** [comment]
Seems I misunderstood the solution, I’ll add support for enabling or disable the setting via a new input which should be available in the latest release.

**Comment by jackton1** [comment]
@C0ZEN The `autocrlf` setting should now be available in the latest release
