### ISSUE TITLE
[BUG] <title>Errors in action.yml

### ISSUE THREAD

**Issue by sorozco07** [tj-actions/verify-changed-files#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I am running this in GitHub actions and see this error

```
Error: tj-actions/verify-changed-files/v9/action.yml (Line: 32, Col: 7): Required property is missing: run
Error: tj-actions/verify-changed-files/v9/action.yml (Line: 32, Col: 7): Required property is missing: shell
Error: tj-actions/verify-changed-files/v9/action.yml (Line: 33, Col: 7): Unexpected value 'uses'
Error: tj-actions/verify-changed-files/v9/action.yml (Line: 35, Col: 7): Unexpected value 'with'
Error: tj-actions/verify-changed-files/v9/action.yml (Line: 32, Col: 7): Required property is missing: run
Error: tj-actions/verify-changed-files/v9/action.yml (Line: 32, Col: 7): Required property is missing: shell
```

I looked at your code and saw that line 32 looks which is the glob match step looks like this:

```
    - name: Glob match
      uses: tj-actions/glob@v7.16
      id: glob
      with:
        files: ${{ inputs.files }}
        separator: "|"
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: verify-changed-files
      shell: bash
      env:
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_FILES: ${{ steps.glob.outputs.paths }}
        INPUT_AUTO_CRLF: ${{ inputs.autocrlf }}
        INPUT_SEPARATOR: ${{ inputs.separator }}
```

I am almost certain that ` - run` should not have `-` .

### To Reproduce

I'm using version 9 of action.yml

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I expected no errors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sorozco07** [comment]
You have a similar error in your other repo for changed-files

**Comment by jackton1** [comment]
@sorozco07 Can you elaborate on what you are trying to do and where you are running the action I.e self hosted runner etc ?

**Comment by jackton1** [comment]
Based on the error your having I’ll suggest verifying if you can run composite actions on the runner version you are using if it’s a case of using a self hosted runner. Giving that this error isn’t an issue of the action and a compatibility problem with running composite actions, I’ll be closing this issue.

**Comment by sorozco07** [comment]
I'm trying to check if a file in my repo changed in an AWS EC2 instance as my runner. I've followed your examples and I kept getting the same error that points to a line in your code. 

Does your comment still apply non-self hosted runners?

**Comment by jackton1** [comment]
You’ll need to upgrade the version of the runner application you have on AWS EC2 
```

curl -o actions-runner-linux-x64-2.290.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.290.1/actions-runner-linux-x64-2.290.1.tar.gz
```
