### ISSUE TITLE
[Feature] Find the files ignored in `.gitignore`

### ISSUE THREAD

**Issue by kunaltyagi** [tj-actions/verify-changed-files#300]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

We have some files which are a nuisance to dev (eg: binaries) but useful for automation. We'd like to know when our ci changes those binaries but current action does not allow that

### Describe the solution you'd like?

A new option:
* include_ignored_files (or similar boolean)

### Describe alternatives you've considered?

Parse `git status --ignored` but that's a new headache :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@kunaltyagi This should now be available in the latest release via the `match-ignore-files` input which is enabled by default.

**Comment by kunaltyagi** [comment]
Thanks a ton @jackton1

**Comment by kunaltyagi** [comment]
Just a simple follow up:

> | match-gitignore-files | string | true | "true" | Indicates whether to match filesin .gitignore |

What should match-gitignore-files be to not match gitignore? Would any string not equal to true work (eg: TRUE, yes, 1)?

**Comment by jackton1** [comment]
Technically any other string other than `“true”` this might change in the future so I’ll suggest using `“false”`
