### ISSUE TITLE
[Feature] ignore files that are uncommitted with no changes

### ISSUE THREAD

**Issue by jamessampford** [tj-actions/verify-changed-files#356]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Have a build script that generates pages and copies scripts over from a `src` folder to a `dist` folder, where another script in the workflow processes the files (adds header + footer as an example)

Trying to only commit where there are actual changes - rather than where files are merely written as I'm getting the `your branch is up to date` error

### Describe the solution you'd like?

Possibly a flag to ignore anything that has no diff for backwards compatibility - ie. if an uncommitted file previously contained "123" and now is written to contain "123" then there is no change (yes uncommitted, but there is no change)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @jamessampford I'll suggest using the `files_changed` output to correctly determine if there are actual changes before running any subsequent scripts. See the [usage](https://github.com/tj-actions/verify-changed-files#usage) section for more information.

> [!NOTE]
> For custom detection i.e. manually comparing file contents. I'll suggest using a script or a third-party action as this action solely detects files that are both tracked and untracked by git and have uncommitted changes.
